spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

nplus1.guard.enabled=true
nplus1.guard.warn-threshold=30
nplus1.guard.fail-threshold=100
nplus1.guard.fail-on-exceed=true
